paths:
  - name: assets
    path: assets

iaFile: ./ia.yaml
docsFolder: ./docs

title: Reacts service documentation

htmlCustomization:
  path: ./htmlCustomization.html
  position: head

header:
  - label: Reacts applications
    position: left
    options:
      - label: Web App
        link: https://webapp.reacts.com/
      - label: Dashboard
        link: https://customer.reacts.com/
    type: hover
  - label: Legal and regulatory
    position: left
    options:
      - label: Privacy Notice
        link: https://www.reacts.com/en/legal/privacy
      - label: End User License Agreement
        link: https://www.reacts.com/en/legal/terms-and-conditions
    type: hover

footer:
  copyrightText: © Koninklijke Philips N.V., 2004 - 2023. All rights reserved.
