name: Generate docs.reacts.com

on:
  push:
    branches:
        - main
  workflow_dispatch:

jobs:
    mark-build:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: [self-hosted, linux, x64, philips]
        permissions:
            contents: read
            id-token: write
            pages: write
        steps:
        - uses: actions/checkout@v3
        - name: Setup NodeJS
          uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Mark Installation
          run: |
            echo '@philips-app:registry = https://artifactory-ehv.ta.philips.com/artifactory/api/npm/dl-innersource-npm' >> ~/.npmrc
            echo '@dls-tokens:registry = https://artifactory-ehv.ta.philips.com/artifactory/api/npm/dl-innersource-npm' >> ~/.npmrc
            echo '@dls-toolkit-react-prototyping:registry = https://artifactory-ehv.ta.philips.com/artifactory/api/npm/dl-innersource-npm' >> ~/.npmrc
            npm i -g --unsafe-perm --loglevel=error @philips-app/mark 
        - name: Mark Setup
          run: |
            mark setup
            mkdir ./dist
        - name: Mark Build
          run: mark build ./config.yaml --output ./dist
        - name: Create Custom 404
          run: |
            cp ./dist/index.html ./dist/404.html
        - name: Pushes to another repository
          uses: cpina/github-action-push-to-another-repository@main
          env:
            SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          with:
            source-directory: 'dist'
            destination-github-username: 'iit-reacts'
            destination-repository-name: 'reacts-support-docs'
            user-email: hsp-reacts-bot@philips.com
            target-branch: main
