name: Generate docs.reacts.com

on:
  push:
    branches:
        - main
        - cleanup
  workflow_dispatch:

jobs:
    mark-build:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: [self-hosted, linux, x64, philips]
        permissions:
            contents: read
            id-token: write
            pages: write
        steps:
        - uses: actions/checkout@v3
        - name: Setup NodeJS
          uses: actions/setup-node@v2
          with:
            node-version: '14'
        - name: Mark Installation
          run: |
            echo '@philips-app:registry = https://artifactory-ehv.ta.philips.com/artifactory/api/npm/dl-innersource-npm' >> ~/.npmrc
            echo '@dls-tokens:registry = https://artifactory-ehv.ta.philips.com/artifactory/api/npm/dl-innersource-npm' >> ~/.npmrc
            echo '@dls-toolkit-react-prototyping:registry = https://artifactory-ehv.ta.philips.com/artifactory/api/npm/dl-innersource-npm' >> ~/.npmrc
            npm i -g --unsafe-perm --loglevel=error @philips-app/mark 
        - name: Mark Setup
          run: |
            mark setup
            mkdir ./dist
        - name: Mark Build
          run: mark build ./config.yaml --output ./dist
        - name: Setup Pages
          uses: actions/configure-pages@v3
        - name: Upload artifact
          uses: actions/upload-pages-artifact@v1
          with:
            # Upload entire repository
            path: './dist/'
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v2